CREATE TABLE Content (
    Id BIGINT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(255) DEFAULT '',
    ContentType int,
    Permalink VARCHAR(255) UNIQUE,
    Body MEDIUMTEXT,
    Rendered MEDIUMTEXT,
    Template VARCHAR(255),
    Status int,
    PublishDate TIMESTAMP null,
    CreatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Category (
    Id BIGINT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(255) NOT NULL,
    Slug VARCHAR(255) NOT NULL,
    ContentType INT NOT NULL
);

CREATE TABLE ContentCategory (
    Id BIGINT PRIMARY KEY AUTO_INCREMENT,
    ContentId BIGINT NOT NULL,
    CategoryId BIGINT NOT NULL,
    FOREIGN KEY (ContentId) REFERENCES Content(Id),
    FOREIGN KEY (CategoryId) REFERENCES Category(Id)
);

CREATE TABLE Section (
    Id BIGINT PRIMARY KEY AUTO_INCREMENT,
    ContentKey VARCHAR(255) UNIQUE,
    ContentBody MEDIUMTEXT
);

CREATE TABLE Component (
    Id BIGINT PRIMARY KEY AUTO_INCREMENT,
    ComponentKey VARCHAR(255) UNIQUE,
    ComponentBody MEDIUMTEXT
);