CREATE TABLE contents (
    Id BIGINT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(255) DEFAULT '',
    ContentType VARCHAR(20),
    Permalink VARCHAR(255) UNIQUE,
    Body MEDIUMTEXT,
    Rendered MEDIUMTEXT,
    Template VARCHAR(255),
    Status VARCHAR(20),
    CreatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);